name: test

on:
  push:
    branches:
      - "master"
  pull_request:
    branches:
      - master

jobs:
  test-node:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node: ["18", "20"]
        typescript: ["4.5", "4.6", "4.7", "4.8", "4.9", "5.0", "5.3"]
    name: Test with TypeScript ${{ matrix.typescript }} on Node ${{ matrix.node }}
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node }}
      - run: yarn install
      - run: yarn add typescript@${{ matrix.typescript }}
      - run: yarn build
      - run: yarn test

  lint:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node: ["18"]
    name: Lint on Node ${{ matrix.node }}
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node }}
      - run: yarn install
      - run: yarn prettier:check
      - run: yarn lint:check
